import type { Metadata } from "next";
import { getServerSession } from "next-auth";

import Header from "@/components/Layout/Header";

import Providers from "../providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <Providers session={session}>
      <Header />
      <main>{children}</main>
    </Providers>
  );
}
