import type { Metadata } from "next";

import Header from "@/components/Layout/Header";

import Providers from "../providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <Header />
      <main className="p-4">{children}</main>
    </Providers>
  );
}
